#!/bin/bash

set -o pipefail
set -exu

#which brew || ( timeout 5m /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" ) || ( echo "Please install Homebrew" ; exit -1 )
which yarn || ( brew install yarn ) || ( npm install -g yarn )
