#!/bin/bash

set -o pipefail
set -exu

which yarn || ( which brew && brew install yarn ) || ( npm install -g yarn )
which pip3 || which pip || ( which brew && brew install python ) || ( echo "Please install 'pip'/'pip3'" && exit -1 )
PIP="$(which pip3 || which pip)"
which git-fame || "$PIP" install --user git-fame

