#!/bin/bash

set -o pipefail
set -exu

cd "$(dirname "$0")/../dist"
DISTDIR="$(pwd)"

GTAR="$(which gtar || which tar)"

find . -type f -name '*.test.*' -ls -exec rm -r \{\} \;
find . -type d -name 'node_modules' -ls -exec rm -r \{\} \;
find . -type f -name 'index.js' -exec dirname \{\} \; | while read
	do
		cd "$DISTDIR/$REPLY"
		DISTNAME="$(basename $REPLY)"
		"$GTAR" -c -v --xz -f "$DISTDIR/$DISTNAME.index.js.xz" ./index.js
		"$GTAR" -c -v --xz -f "$DISTDIR/$DISTNAME.tar.xz" .
	done
