# @format
---
name: Code Cleanup

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: ./script/bootstrap
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0
      - run: yarn build:docs
      - run: git add -u .
      - run: yarn lint-staged
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(cleanup): automatic code cleanup"
