# @format
---
name: Update Documentation

on:
  push:
    branches:
      - latest

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0
      - run: yarn build:docs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(auto-update): update the documentation"
