# @format
---
name: Release

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
    paths:
      - "**.ts"
      - "**.config.*"
      - package.json
      - tsconfig.json
      - "*.md"
      - ".github/workflows/release.yml"

jobs:
  perform_release:
    if:
      github.event_name == 'push' && contains(github.event.commits[0].message,
      '[skip ci]') == false
    outputs:
      released: ${{ steps.release.outputs.new_release_published }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name: Install Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Polish Files
        run: yarn polish
      - name: Build Distribution Bundles
        run: yarn build:bundle
      - name: Perform Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v2.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  generate_docs:
    needs:
      - perform_release
    if: needs.perform_release.outputs.released
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: ./script/bootstrap
      - run: yarn install --frozen-lockfile
      - run: yarn build:docs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(auto-update): update the documentation"
