# @format
---
name: Release

on:
  push:

jobs:
  perform-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Action For Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
