# @format
---
name: Release

on:
  push:
    paths:
      - "**.ts"
      - package.json
      - tsconfig.json
      - "**.config.js"
      - "**.config.cjs"
    tags-ignore:
      - v*

jobs:
  perform-release:
    if:
      github.event_name == 'push' && contains(github.event.commits[0].message,
      '[skip ci]') == false
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name: Install Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Perform Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
